# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

# Build and Test code
# This workflow doesn't support:
# * GPU build and tests
# * Salmon WinService
# * SalmonWin Java and C# tests
# * Salmon HttpFS and WSFS tests (need HTTP server and WebFS service in a container)
# * Android tests
# * .NET Android tests
# * JS Web Browser tests

# Note: if you have cache misses then make sure this workflow runs in the main branch first for the same cache keys.
name: CI.BuildTest

on:
  push:
    branches: [ "wip-3.0.2" ]
  pull_request:
    branches: [ "wip-3.0.2" ]

env:
  WIN_TEST_DIR: C:\tmp\salmon\test
  LINUX_TEST_DIR: /tmp/salmon/test
jobs:

  # Java
  java_native_build_matrix:
    strategy:
      matrix:
        java_version: [11]
        os: [windows-latest,ubuntu-latest,ubuntu-24.04-arm,macos-15-intel,macos-latest]
    name: build.java${{ matrix.java_version }}. ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read 
    steps:
    
    # Git
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - if: runner.os == 'Windows'
      name: Get submodules on Windows
      shell: cmd
      run: cd ./scripts/misc && init_gitmodules.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Get submodules on Linux/MacOS
      shell: bash
      run: cd ./scripts/misc && ./init_gitmodules.sh
    
    # Toolchains and Build envs
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    
    # Caches
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    # Gradle Build
    - if: runner.os == 'Windows'
      name: Build Java Libraries on Windows
      shell: cmd
      run: cd ./libs/projects/salmon-libs-gradle && gradlew.bat build -x test -i
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Build Java Libraries on Linux/MacOS
      shell: bash
      run: cd ./libs/projects/salmon-libs-gradle && ./gradlew build -x test -i
      
    # Build GCC native libraries
    - if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
      name: Build GCC Native Libraries on Linux aarch64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=linux ARCH=aarch64 ENABLE_JNI=1 package
    - if: ${{ matrix.os == 'macos-15-intel' }}
      name: Build GCC Native Libraries on MacOS x86_64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=macos ARCH=x86_64 ENABLE_JNI=1 package
    - if: ${{ matrix.os == 'macos-latest' }}
      name: Build GCC Native Libraries on MacOS aarch64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=macos ARCH=aarch64 ENABLE_JNI=1 package
      
    # Test
    - if: runner.os == 'Windows'
      name: Test Java Libraries on Windows
      shell: cmd
      run: cd ./scripts/tests/java/win && test_java_ci.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Test Java Libraries on Linux/MacOS
      shell: bash
      run: cd ./scripts/tests/java/linux_mac && ./test_java_ci.sh


  # C# .NET
  dotnet_android_native_build_matrix:
    strategy:
      matrix:
        dotnet_version: [8.0.x]
        os: [windows-latest,ubuntu-latest,ubuntu-24.04-arm,macos-15-intel,macos-latest]
    name: build.dotnet${{ matrix.dotnet_version }}.${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read 
    steps:
    
    # Git
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - if: runner.os == 'Windows'
      name: Get submodules on Windows
      shell: cmd
      run: cd ./scripts/misc && init_gitmodules.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Get submodules on Linux/MacOS
      shell: bash
      run: cd ./scripts/misc && ./init_gitmodules.sh
    
    # Toolchains and Build envs
    - if: runner.os == 'Windows'
      name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Setup Nuget
      uses: nuget/setup-nuget@v2
    - if: runner.os == 'Windows'
      name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1.2
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      
    # Caches
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Cache Nuget packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.vcxproj*', '**/*.csproj', '**/packages.config') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Gradle Build
    - if: runner.os == 'Windows'
      name: Build Gradle Android Native Libraries on Windows
      shell: cmd
      run: cd ./libs/projects/salmon-libs-gradle-android && gradlew.bat :salmon-native-android:build --settings-file settings-native.gradle -x test -i
      
    # MSBuild Build
    - if: runner.os == 'Windows'
      name: Restore .NET dependencies
      working-directory: ./libs/projects/SalmonLibs.VS2022
      run: msbuild -t:restore
    - if: runner.os == 'Windows'
      name: Build .NET on Windows
      working-directory: ./libs/projects/SalmonLibs.VS2022
      run: msbuild /property:Configuration=Debug /p:Platform=x64
    - if: runner.os == 'Windows'
      name: Copy Native Libraries to SalmonTest
      shell: bash
      run: cd ./libs/projects/SalmonLibs.VS2022 && copy /Y .\x64\Debug\SalmonNative.* .\Salmon.Test\bin\Debug\net8.0-windows\
    
    # DotNet Build
    # SalmonCore
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Salmon.Core Restore workload dependencies
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.Core
      run: dotnet workload restore
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Salmon.Core Restore dependencies
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.Core
      run: dotnet restore
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Salmon.Core Build
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.Core
      run: dotnet build --no-restore -c Debug
    # SalmonFS
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Salmon.FS Restore workload dependencies
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.FS
      run: dotnet workload restore
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Salmon.FS Restore dependencies
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.FS
      run: dotnet restore
    - if: runner.os == 'Linux' || runner.os == 'macOS'  
      name: Salmon.FS Build
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.FS
      run: dotnet build --no-restore -c Debug
    # SalmonTest
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Salmon.Test Restore workload dependencies
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.Test
      run: dotnet workload restore
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Salmon.Test Restore dependencies
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.Test
      run: dotnet restore
    - if: runner.os == 'Linux' || runner.os == 'macOS'  
      name: Salmon.Test Build
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.Test
      run: dotnet build --no-restore -c Debug
    
    
    # Build GCC native libraries
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Build GCC Native Libraries on Linux x86_64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=linux ARCH=x86_64 ENABLE_JNI=1 package && cp -f ./lib/x86_64/libsalmon.so ../SalmonLibs.VS2022/Salmon.Test/bin/Debug/net8.0-windows/SalmonNative.dll
    - if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
      name: Build GCC Native Libraries on Linux aarch64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=linux ARCH=aarch64 ENABLE_JNI=1 package && cp -f ./lib/aarch64/libsalmon.so ../SalmonLibs.VS2022/Salmon.Test/bin/Debug/net8.0-windows/SalmonNative.dll
    - if: ${{ matrix.os == 'macos-15-intel' }}
      name: Build GCC Native Libraries on MacOS x86_64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=macos ARCH=x86_64 ENABLE_JNI=1 package && cp -f ./lib/x86_64/libsalmon.dylib ../SalmonLibs.VS2022/Salmon.Test/bin/Debug/net8.0-windows/SalmonNative.dll
    - if: ${{ matrix.os == 'macos-latest' }}
      name: Build GCC Native Libraries on MacOS aarch64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=macos ARCH=aarch64 ENABLE_JNI=1 package && cp -f ./lib/aarch64/libsalmon.dylib ../SalmonLibs.VS2022/Salmon.Test/bin/Debug/net8.0-windows/SalmonNative.dll
      
    # Test
    - if: runner.os == 'Windows'
      name: Test .NET Libraries on Windows
      shell: cmd
      run: cd ./scripts/tests/csharp/win && test_csharp_ci.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Test .NET Libraries on Linux/MacOS
      shell: bash
      run: cd ./scripts/tests/csharp/linux_mac && ./test_csharp_ci.sh

   
  # Python
  python_native_build_matrix:
    strategy:
      matrix:
        python_version: [3.11]
        os: [windows-latest,ubuntu-latest,ubuntu-24.04-arm,macos-15-intel,macos-latest]
    name: build.python${{ matrix.python_version }}.${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read 
    steps:
    
    # Git
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - if: runner.os == 'Windows'
      name: Get submodules on Windows
      shell: cmd
      run: cd ./scripts/misc && init_gitmodules.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Get submodules on Linux/MacOS
      shell: bash
      run: cd ./scripts/misc && ./init_gitmodules.sh
    
    # Toolchains and Build envs
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python_version }}
        cache: 'pip'
    - run: python -m pip install typeguard pycryptodome wrapt
    
    # Caches
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Gradle Build
    - if: runner.os == 'Windows'
      name: Build Gradle Native Libraries on Windows
      shell: cmd
      run: cd ./libs/projects/salmon-libs-gradle && gradlew.bat :salmon-native:build -x test -i
    
    # Build xcode native libraries (needs OpenCL)
    # - if: ${{ matrix.os == 'macos-15-intel' }}
      # name: Build GCC Native Libraries on MacOS x86_64
      # shell: bash
      # run: cd ./libs/projects/salmon-libs-xcode-macos/salmon && xcodebuild -verbose -scheme salmon build && ./package.sh
    # - if: ${{ matrix.os == 'macos-latest' }}
      # name: Build GCC Native Libraries on MacOS aarch64
      # shell: bash
      # run: cd ./libs/projects/salmon-libs-xcode-macos/salmon && xcodebuild -verbose -scheme salmon build && ./package.sh
    
    # Build GCC native libraries
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Build GCC Native Libraries on Linux x86_64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=linux ARCH=x86_64 ENABLE_JNI=1 package
    - if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
      name: Build GCC Native Libraries on Linux aarch64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=linux ARCH=aarch64 ENABLE_JNI=1 package
    - if: ${{ matrix.os == 'macos-15-intel' }}
      name: Build GCC Native Libraries on MacOS x86_64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=macos ARCH=x86_64 ENABLE_JNI=1 package
    - if: ${{ matrix.os == 'macos-latest' }}
      name: Build GCC Native Libraries on MacOS aarch64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=macos ARCH=aarch64 ENABLE_JNI=1 package
    
    # Test
    - if: runner.os == 'Windows'
      name: Test Python Libraries on Windows
      shell: cmd
      run: cd ./scripts/tests/python/win && test_python_ci.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Test Python Libraries on Linux/MacOS
      shell: bash
      run: cd ./scripts/tests/python/linux_mac && ./test_python_ci.sh


  # JavaScript
  js_native_build_matrix:
    strategy:
      matrix:
        node_version: [21.x]
        os: [windows-latest,ubuntu-latest,ubuntu-24.04-arm,macos-15-intel,macos-latest]
    name: build.js${{ matrix.node_version }}.${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read 
    steps:
    
    # Git
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - if: runner.os == 'Windows'
      name: Get submodules on Windows
      shell: cmd
      run: cd ./scripts/misc && init_gitmodules.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Get submodules on Linux/MacOS
      shell: bash
      run: cd ./scripts/misc && ./init_gitmodules.sh
    
    # Toolchains and Build envs
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
    
    # Caches
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Gradle Build
    - if: runner.os == 'Windows'
      name: Build Gradle Native Libraries on Windows
      shell: cmd
      run: cd ./libs/projects/salmon-libs-gradle && gradlew.bat :salmon-native:build -x test -i
    
    # Build xcode native libraries (needs OpenCL)
    # - if: ${{ matrix.os == 'macos-15-intel' }}
      # name: Build GCC Native Libraries on MacOS x86_64
      # shell: bash
      # run: cd ./libs/projects/salmon-libs-xcode-macos/salmon && xcodebuild -verbose -scheme salmon build && ./package.sh
    # - if: ${{ matrix.os == 'macos-latest' }}
      # name: Build GCC Native Libraries on MacOS aarch64
      # shell: bash
      # run: cd ./libs/projects/salmon-libs-xcode-macos/salmon && xcodebuild -verbose -scheme salmon build && ./package.sh
    
    # Build GCC native libraries
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Build GCC Native Libraries on Linux x86_64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=linux ARCH=x86_64 ENABLE_JNI=1 package
    - if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
      name: Build GCC Native Libraries on Linux aarch64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=linux ARCH=aarch64 ENABLE_JNI=1 package
    - if: ${{ matrix.os == 'macos-15-intel' }}
      name: Build GCC Native Libraries on MacOS x86_64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=macos ARCH=x86_64 ENABLE_JNI=1 package
    - if: ${{ matrix.os == 'macos-latest' }}
      name: Build GCC Native Libraries on MacOS aarch64
      shell: bash
      run: cd ./libs/projects/salmon-libs-gcc && make PLATFORM=macos ARCH=aarch64 ENABLE_JNI=1 package
    
    # Install Node modules
    - name: Install Node modules
      working-directory: ./libs/projects/SalmonLibs.vscode
      run: npm install
      
    # Transpile
    - name: Build TS to JS
      run: cd ./libs/projects/SalmonLibs.vscode && npm run build  
    
    # Test
    - if: runner.os == 'Windows'
      name: Test JS Libraries on NodeJS on Windows
      shell: cmd
      run: cd ./scripts/tests/javascript/win && test_javascript_ci.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Test JS Libraries on NodeJS on Linux/MacOS
      shell: bash
      run: cd ./scripts/tests/javascript/linux_mac && ./test_javascript_ci.sh