# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: BuildTest

on:
  push:
    branches: [ "wip-3.0.2" ]
  pull_request:
    branches: [ "wip-3.0.2" ]

env:
  TEST_DIR="C:/tmp/salmon/test"  

jobs:
  java_build_matrix:
    strategy:
      matrix:
        java_version: [11, 17]
        os: [ubuntu-latest, windows-latest, darwin-latest]
    name: build.java.${{ matrix.java_version }}. ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    defaults:
      run:
        working-directory: libs/projects/salmon-libs-gradle
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - if: runner.os == 'Windows'
      name: Download dependencies
      working-directory: scripts/misc
      run: init_gitmodules.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Download dependencies
      working-directory: scripts/misc
      run: ./init_gitmodules.sh
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Build Salmon native with Gradle Wrapper
      run: .\gradlew.bat build -x test -x salmon-native -i  

  java_test_matrix:
    strategy:
      matrix:
        java_version: [11, 17]
        os: [ubuntu-latest, windows-latest, darwin-latest]
        enc_threads: [1, 2, 4]
        aes_provider_type: [Default, Aes, AesIntrinsics]
    name: test.java.${{ matrix.java_version }}.${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    defaults:
      run:
        working-directory: libs/projects/salmon-libs-gradle
    - name: Salmon.Core.Native
      run: .\gradlew.bat :salmon-core:test --tests "com.mku.salmon.test.SalmonNativeTests" -DAES_PROVIDER_TYPE=${{ matrix.aes_provider_type }} -DENC_THREADS=${{ matrix.enc_threads }} -i
    - name: Salmon.Core
      run: .\gradlew.bat :salmon-core:test --tests "com.mku.salmon.test.SalmonCoreTests" -DAES_PROVIDER_TYPE=${{ matrix.aes_provider_type }} -DENC_THREADS=${{ matrix.enc_threads }} -i
    - name: Salmon.FS
      run: .\gradlew.bat :salmon-fs:test --tests "com.mku.salmon.test.SalmonFSTests" -DAES_PROVIDER_TYPE=${{ matrix.aes_provider_type }} -DENC_THREADS=${{ matrix.enc_threads }} -i -DtestDir=$TEST_DIR

