# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: BuildTest

on:
  push:
    branches: [ "wip-3.0.2" ]
  pull_request:
    branches: [ "wip-3.0.2" ]

env:
  
  TEST_DIR: C:\tmp\salmon\test
  ENABLE_GPU: true
  OPENCL_SDK_WIN_VERSION: OpenCL-SDK-v2025.07.23-Win-x64
  
  # TODO: move to container
  # WS_SERVER_URL: http://localhost:8080
  # HTTP_PORT: 8880
  # HTDOCS: C:\tmp\salmon
jobs:
  java_build_matrix:
    strategy:
      matrix:
        java_version: [11]
        os: [windows-latest,ubuntu-latest,ubuntu-24.04-arm,macos-15-intel]
    name: build.java.${{ matrix.java_version }}. ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read 
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - if: runner.os == 'Windows'
      name: Get submodules on Windows
      shell: cmd
      run: cd ./scripts/misc && init_gitmodules.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Get submodules on Linux/MacOS
      shell: bash
      run: cd ./scripts/misc && ./init_gitmodules.sh
    - if: runner.os == 'Windows'
      name: Get OpenCL for Windows
      shell: cmd
      run: cd ./scripts/misc && get_opencl.bat
    - if: runner.os == 'Linux'
      name: Get OpenCL for Linux
      shell: bash
      run: sudo apt install -y ocl-icd-opencl-dev
    - if: runner.os == 'macOS'
      name: Get OpenCL for MacOS
      shell: bash
      run: echo "OpenCL already installed"
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - if: runner.os == 'Windows'
      name: Build Java Libraries on Windows
      shell: cmd
      run: cd ./libs/projects/salmon-libs-gradle && gradlew.bat build -x test -DENABLE_GPU=$ENABLE_GPU -DOPENCL_INCLUDE=\\..\\..\\libs\\deps\\OpenCL\\$OPENCL_SDK_WIN_VERSION\\include -DOPENCL_LIB=\\..\\..\\libs\\deps\\OpenCL\\$OPENCL_SDK_WIN_VERSION\\lib -i
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Build Java Libraries on Linux/MacOS
      shell: bash
      run: cd ./libs/projects/salmon-libs-gradle && ./gradlew build -x test -DENABLE_GPU=$ENABLE_GPU -DOPENCL_INCLUDE=/usr/include -DOPENCL_LIB=/usr/lib/x86_64-linux-gnu/ -i
    # TODO: move to container
    # - if: runner.os == 'Windows'
      # name: Setup WebFS service
      # shell: cmd
      # run: cd ./scripts/misc && setup_webfs.bat
    # - if: runner.os == 'Windows'
      # name: Setup Http service
      # shell: cmd
      # run: npm install -g http-server
    # - if: runner.os == 'Windows'
      # name: Setup directories
      # shell: cmd
      # run: mkdir $HTDOCS && mkdir $TEST_DIR
    # - if: runner.os == 'Windows'
      # name: Start Http Server
      # run: cd ./scripts/misc && start_http_server.bat &
    - if: runner.os == 'Windows'
      name: Test Java Libraries on Windows
      shell: cmd
      run: cd ./scripts/tests/java/win && test_java_ci.bat
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Test Java Libraries on Linux/MacOS
      shell: bash
      run: cd ./scripts/tests/java/linux && test_java_ci.sh