# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java Gradle Linux

on:
  push:
    branches: [ "wip-3.0.2" ]
  pull_request:
    branches: [ "wip-3.0.2" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: libs/projects/salmon-libs-gradle

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
        
    - name: set exec permissions
      run: chmod +x ./gradlew
      
    # build without salmon-win
    - name: Build with Gradle Wrapper
      run: ./gradlew build -x :salmon-win:build -x test -i


    # tests
    # core
    - name: Salmon.Core Default Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonCoreTests" -DAES_PROVIDER_TYPE=Default -DENC_THREADS=1 -i
    - name: Salmon.Core Default Multithreaded Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonCoreTests" -DAES_PROVIDER_TYPE=Default -DENC_THREADS=2 -i
      
    - name: Salmon.Core Aes Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonCoreTests" -DAES_PROVIDER_TYPE=Aes -DENC_THREADS=1 -i
    - name: Salmon.Core Aes Multithreaded Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonCoreTests" -DAES_PROVIDER_TYPE=Aes -DENC_THREADS=2 -i

    - name: Salmon.Core AesIntrinsics Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonCoreTests" -DAES_PROVIDER_TYPE=Aes -DENC_THREADS=1 -i
    - name: Salmon.Core AesIntrinsics Multithreaded Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonCoreTests" -DAES_PROVIDER_TYPE=AesIntrinsics -DENC_THREADS=2 -i


    # fs     
    - name: Salmon.FS Test
      run: ./gradlew :salmon-fs:test --tests "com.mku.salmon.test.SalmonFSTests" -DENC_THREADS=1 -i -DtestDir="/tmp/salmon/test"
    - name: Salmon.FS Multithreaded Test
      run: ./gradlew :salmon-fs:test --tests "com.mku.salmon.test.SalmonFSTests" -DENC_THREADS=2 -i -DtestDir="/tmp/salmon/test"
      
    # native
    - name: Salmon.Native Aes Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonNativeTests" -DAES_PROVIDER_TYPE=Aes -DENC_THREADS=1 -i
    - name: Salmon.Native Aes Multithreaded Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonNativeTests" -DAES_PROVIDER_TYPE=Aes -DENC_THREADS=2 -i
      
    - name: Salmon.Native AesIntrinsics Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonNativeTests" -DAES_PROVIDER_TYPE=AesIntrinsics -DENC_THREADS=1 -i
    - name: Salmon.Native AesIntrinsics Multithreaded Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonNativeTests" -DAES_PROVIDER_TYPE=AesIntrinsics -DENC_THREADS=2 -i